name: threema_connector
author: Johannes Charra
email: johannes.charra@gmail.com
url: http://example.com
version: "0.1"
title: "threema_connector"
icon: mobile
# dependency on Core is required for UI plugins
dependencies:
  - !PluginDependency { plugin_name: core }
  # - !OptionalPluginDependency {
  #   plugin_name: my_other_plugin
  # }
  # - !ModuleDependency {
  #   module_name: requests
  # }
  # - !BinaryDependency {
  #   binary_name: curl
  # }
resources:
  - "resources/js/module.js"
  - "resources/js/routing.js"
  - "resources/js/controllers/index.controller.js"
  - "resources/js/controllers/missing.controller.js"
  - "resources/js/controllers/unmatched.controller.js"
  - "resources/js/controllers/credentialsChange.controller.js"
  - "resources/js/controllers/credentialsDelete.controller.js"
  - "resources/partial/index.html"
  - "resources/partial/missing.html"
  - "resources/partial/unmatched.html"
  - "resources/partial/credentialsChange.modal.html"
  - "resources/partial/credentialsDelete.modal.html"
  - "resources/css/styles.css"
  - "ng:example.threema_connector"
