name: threema_connector
author: Johannes Charra
email: johannes.charra@gmail.com
url: http://example.com
version: "0.1"
title: "threema_connector"
icon: mobile
# dependency on Core is required for UI plugins
dependencies:
  - !PluginDependency { plugin_name: core }
  - !OptionalPluginDependency { plugin_name: lmn_common }
  # - !OptionalPluginDependency {
  #   plugin_name: my_other_plugin
  # }
  # - !ModuleDependency {
  #   module_name: requests
  # }
  # - !BinaryDependency {
  #   binary_name: curl
  # }
resources:
  - "resources/js/module.js"
  - "resources/js/routing.js"
  - "resources/js/controllers/index.controller.js"
  - "resources/js/controllers/missing.controller.js"
  - "resources/js/controllers/unmatched.controller.js"
  - "resources/js/controllers/suggestions.controller.js"
  - "resources/js/controllers/credentialsChange.controller.js"
  - "resources/js/controllers/credentialsDelete.controller.js"
  - "resources/js/controllers/userList.controller.js"
  - "resources/js/controllers/groups.controller.js"
  - "resources/js/controllers/contacts.controller.js"
  - "resources/js/controllers/normalizations.controller.js"
  - "resources/js/directives/studentsList.js"
  - "resources/js/directives/teachersList.js"
  - "resources/js/directives/groups.js"
  - "resources/js/directives/contacts.js"
  - "resources/js/services/classService.js"
  - "resources/partial/index.html"
  - "resources/partial/missing.html"
  - "resources/partial/unmatched.html"
  - "resources/partial/suggestions.html"
  - "resources/partial/credentialsChange.modal.html"
  - "resources/partial/credentialsDelete.modal.html"
  - "resources/partial/userList.html"
  - "resources/partial/contacts.html"
  - "resources/partial/groups.html"
  - "resources/partial/normalizations.html"
  - "resources/css/styles.css"
  - "ng:dfglfa.threema_connector"
