name: threema_connector
author: Johannes Charra
email: johannes.charra@gmail.com
url: http://example.com
version: "0.1"
title: "threema_connector"
icon: mobile
# dependency on Core is required for UI plugins
dependencies:
  - !PluginDependency { plugin_name: core }
  # - !OptionalPluginDependency {
  #   plugin_name: my_other_plugin
  # }
  # - !ModuleDependency {
  #   module_name: requests
  # }
  # - !BinaryDependency {
  #   binary_name: curl
  # }
resources:
  - "resources/js/module.es"
  - "resources/js/routing.es"
  - "resources/js/controllers/index.controller.es"
  - "resources/js/controllers/consistency.controller.es"
  - "resources/partial/index.html"
  - "resources/partial/consistency.html"
  - "resources/css/styles.css"
  - "ng:example.threema_connector"
